---
title: Bias Detection
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Bias Detection
  logo_img: "/Asset 1@2x.png"
  has_nav: true
  menu:
    actions:
    - label: Sign Up
      url: "/signup"
footer:
  logo_img: images/logo_alt.png
  tagline: Bias Detection
  has_nav: true
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Bias Detection. All rights reserved."
  links:
  - text: Pocket Notebooks
    url: https://backpocket.co
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
